### ISSUE TITLE
cstrHEADER ???

### ISSUE THREAD

**Issue by WHots** [KunYi/DumpSMBIOS#10]
where is cstrHEADER defined at?

**Comment by KunYi** [comment]
please check source code first
cstrHEADER just for "====================="
./LegacyMethod/DumpSMBIOS.cpp:18:const UINT cstrHEADER = 0xFFFF;
./LegacyMethod/DumpSMBIOS.cpp:46:	if (cstrHEADER == type)
./LegacyMethod/DumpSMBIOS.cpp:477:			printf("%s\n", getHeaderString(cstrHEADER));
./DumpSMBIOS/DumpSMBIOS.cpp:200:const UINT cstrHEADER = 0xFFFF;
./DumpSMBIOS/DumpSMBIOS.cpp:231:	if (cstrHEADER == type)
./DumpSMBIOS/DumpSMBIOS.cpp:602:			_tprintf(TEXT("%s\n"), getHeaderString(cstrHEADER));
