### ISSUE TITLE
Getting junk in SMBIOSTableData for SMBIOS 2.8

### ISSUE THREAD

**Issue by nehaheights** [KunYi/DumpSMBIOS#6]
Hi,
I have SMBIOS 2.8 on my machine.
If I run this code GetSystemFirmwareTable returns junk in SMBIOSTableData buffer.
Do you have any idea about the issue.

Thanks and Regards
Neha

**Comment by KunYi** [comment]
GetSystemFirmwareTable would be get SMBIOS 2.x ~ 3.0 version, latest version test for Asus X99 motherboard with SMBIOS 3.0 passed.
maybe you can provide the the raw data for debugging

**Comment by nehaheights** [comment]
Thanks for replying KunYi :)
What data should I provide ?

**Comment by nehaheights** [comment]
[SMBIOSdata.txt](https://github.com/KunYi/DumpSMBIOS/files/1602632/SMBIOSdata.txt)
Have attached SMBiosData

**Comment by KunYi** [comment]
Hi, the SMBIOSdata, should be not from GetSystemFirmwareTable, the data should be from  windows registry 
see you data
![default](https://user-images.githubusercontent.com/2186922/34553556-15cf7954-f163-11e7-83ed-8c403957f404.png)

**Comment by KunYi** [comment]
if use text editor, we can observer the below content, the code need to convert to raw
but if you use  GetSystemFirmwareTable() will to get raw data (binary format) 
And to ref. https://github.com/KunYi/DumpSMBIOS/issues/5
you can just save raw to file or convert to .h format, thank you!


[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\mssmbios\Data]
"SMBiosData"=hex:00,02,08,00,49,14,00,00,da,fb,00,da,b2,00,37,cf,1e,b6,00,05,\
  00,05,00,03,00,06,00,06,00,05,00,0f,00,0f,00,00,00,11,00,11,00,02,00,12,00,\
  12,00,04,00,22,00,22,00,01,00,23,00,23,00,00,00,28,00,28,00,00,00,29,00,29,\
  00,01,00,2a,00,2a,00,02,00,2b,00,2b,00,ff,ff,2c,00,2c,00,ff,ff,2d,00,2d,00,\
  02,00,2e,00,2e,00,00,00,42,00,42,00,01,00,43,00,43,00,00,00,55,00,55,00,00,\
  00,5c,00,5c,00,01,00,5d,00,5d,00,00,00,6d,00,6d,00,05,00,6e,00,6e,00,01,00,\
  7d,00,7d,00,ff,ff,87,00,87,00,00,00,88,00,88,00,01,00,90,00,90,00,01,00,91,\
  00,91,00,00,00,92,00,92,00,02,00,93,00,93,00,01,00,94,00,94,00,00,00,97,00,\
  97,00,01,00,98,00,98,00,00,00,9b,00,9b,00,01,00,9c,00,9c,00,00,00,9d,00,9d,\
  00,01,00,9e,00,9e,00,00,00,9f,00,9f,00,00,00,a0,00,a0,00,01,00,a1,00,a1,00,\
  00,00,a2,00,a2,00,02,00,ff,ff,ff,ff,00,00,00,00,da,fb,01,da,b2,00,37,cf,1e,\
  b6,00,a3,00,a3,00,01,00,d1,00,d1,00,01,00,d2,00,d2,00,00,00,e4,00,e4,00,01,\
  00,e5,00,e5,00,00,00,ea,00,ea,00,00,00,eb,00,eb,00,01,00,ec,00,ec,00,02,00,\
  ed,00,ed,00,00,00,f0,00,f0,00,01,00,f5,00,f5,00,04,00,f6,00,f6,00,00,00,17,\
  01,17,01,00,00,18,01,18,01,01,00,19,01,19,01,00,00,1a,01,1a,01,01,00,1b,01,\
  1b,01,00,00,1c,01,1c,01,01,00,1d,01,1d,01,00,00,1e,01,1e,01,01,00,1f,01,1f,\
  01,00,00,20,01,20,01,01,00,21,01,21,01,00,00,22,01,22,01,01,00,2b,01,2b,01,\
  01,00,2c,01,2c,01,00,00,2d,01,2d,01,01,00,2e,01,2e,01,00,00,35,01,35,01,ff,\
  00,37,01,37,01,00,00,38,01,38,01,01,00,39,01,39,01,02,00,40,01,40,01,00,00,\
  41,01,41,01,01,00,44,01,44,01,00,00,45,01,45,01,01,00,46,01,46,01,00,00,47,\
  01,47,01,01,00,4a,01,4a,01,00,00,ff,ff,ff,ff,00,00,00,00,da,fb,02,da,b2,00,\
  37,cf,1e,b6,00,4b,01,4b,01,01,00,4e,01,4e,01,00,00,4f,01,4f,01,01,00,54,01,\
  54,01,00,00,55,01,55,01,01,00,68,01,68,01,00,00,69,01,69,01,01,00,71,01,71,\
  01,00,00,72,01,72,01,01,00,73,01,73,01,00,00,74,01,74,01,01,00,75,01,75,01,\
  02,00,76,01,76,01,01,00,9b,01,9b,01,00,00,9c,01,9c,01,01,00,c4,01,c4,01,00,\
  00,c5,01,c5,01,01,00,e8,01,e8,01,00,00,e9,01,e9,01,01,00,ea,01,ea,01,00,00,\
  eb,01,eb,01,01,00,02,02,02,02,00,00,03,02,03,02,01,00,04,02,04,02,00,00,05,\
  02,05,02,01,00,2d,02,2d,02,01,00,2e,02,2e,02,00,00,31,02,31,02,04,00,32,02,\
  32,02,02,00,33,02,33,02,01,00,4a,02,4a,02,01,00,4b,02,4b,02,01,00,4c,02,4c,\
  02,00,00,64,02,64,02,01,00,65,02,65,02,00,00,66,02,66,02,01,00,67,02,67,02,\
  00,00,68,02,68,02,01,00,69,02,69,02,00,00,ff,ff,ff,ff,00,00,00,00,da,fb,03,\
  da,b2,00,37,cf,1e,b6,00,6c,02,6c,02,01,00,6d,02,6d,02,00,00,6e,02,6e,02,00,\
  00,75,02,75,02,00,00,76,02,76,02,01,00,a3,02,a3,02,01,00,a4,02,a4,02,00,00,\
  a7,02,a7,02,01,00,a8,02,a8,02,00,00,bd,02,bd,02,01,00,be,02,be,02,00,00,cd,\
  02,cd,02,01,00,d8,02,d8,02,ff,ff,d9,02,d9,02,ff,ff,da,02,da,02,ff,ff,db,02,\
  db,02,ff,ff,dc,02,dc,02,ff,ff,dd,02,dd,02,ff,ff,de,02,de,02,ff,ff,df,02,df,\
  02,ff,ff,e3,02,e3,02,01,00,e4,02,e4,02,00,00,e5,02,e5,02,01,00,fd,02,fd,02,\
  01,00,fe,02,fe,02,00,00,0f,03,0f,03,02,00,12,03,12,03,03,00,13,03,13,03,01,\
  00,14,03,14,03,00,00,15,03,15,03,01,00,16,03,16,03,00,00,17,03,17,03,01,00,\
  18,03,18,03,00,00,19,03,19,03,01,00,1a,03,1a,03,00,00,1b,03,1b,03,01,00,1c,\
  03,1c,03,00,00,1d,03,1d,03,01,00,1e,03,1e,03,00,00,ff,ff,ff,ff,00,00,00,00,\
  da,fb,04,da,b2,00,37,cf,1e,b6,00,1f,03,1f,03,01,00,20,03,20,03,00,00,26,03,\
  26,03,01,00,2d,03,2d,03,01,00,2e,03,2e,03,00,00,32,03,32,03,00,00,33,03,33,\
  03,03,00,34,03,34,03,01,00,35,03,35,03,02,00,38,03,38,03,01,00,39,03,39,03,\
  01,00,4f,03,4f,03,01,00,51,03,51,03,00,00,52,03,52,03,01,00,57,03,57,03,00,\
  00,58,03,58,03,01,00,61,03,61,03,01,00,62,03,62,03,00,00,69,03,69,03,00,00,\
  6a,03,6a,03,01,00,6b,03,6b,03,02,00,6f,03,6f,03,ff,ff,81,03,81,03,00,00,82,\
  03,82,03,01,00,83,03,83,03,07,00,84,03,84,03,00,00,85,03,85,03,01,00,a2,03,\
  a2,03,01,00,a3,03,a3,03,00,00,be,03,be,03,ff,ff,c1,03,c1,03,01,00,c2,03,c2,\
  03,02,00,c3,03,c3,03,03,00,c4,03,c4,03,ff,ff,c5,03,c5,03,00,00,cf,03,cf,03,\
  01,00,d0,03,d0,03,00,00,d1,03,d1,03,01,00,d2,03,d2,03,00,00,ff,ff,ff,ff,00,\
  00,00,00,da,7d,05,da,b2,00,37,cf,1e,b6,00,f6,03,f6,03,01,00,f7,03,f7,03,00,\
  00,05,04,05,04,05,00,06,04,06,04,04,00,1a,04,1a,04,01,00,1b,04,1b,04,00,00,\
  21,04,21,04,02,00,2b,04,2b,04,ff,ff,2e,04,2e,04,01,00,2f,04,2f,04,00,00,00,\
  80,00,80,00,00,02,80,02,80,02,00,03,80,03,80,03,00,0c,80,0c,80,00,00,0e,80,\
  0e,80,01,00,00,a0,00,a0,01,00,04,a0,04,a0,01,00,06,f0,06,f0,00,00,ff,ff,ff,\
  ff,00,00,00,00,da,fb,06,da,b2,00,37,cf,1e,b6,00,00,f1,00,f1,01,00,02,f1,02,\
  f1,01,00,03,f1,03,f1,01,00,05,f1,05,f1,01,00,10,f1,10,f1,01,00,12,f1,12,f1,\
  01,00,13,f1,13,f1,01,00,15,f1,15,f1,01,00,20,f1,20,f1,01,00,22,f1,22,f1,01,\
  00,23,f1,23,f1,01,00,25,f1,25,f1,01,00,30,f1,30,f1,01,00,32,f1,32,f1,01,00,\
  33,f1,33,f1,01,00,35,f1,35,f1,01,00,40,f1,40,f1,01,00,42,f1,42,f1,01,00,43,\
  f1,43,f1,01,00,45,f1,45,f1,01,00,00,f6,00,f6,01,00,01,f6,01,f6,01,00,02,f6,\
  02,f6,01,00,04,f6,04,f6,01,00,10,f6,10,f6,01,00,11,f6,11,f6,01,00,12,f6,12,\
  f6,01,00,14,f6,14,f6,01,00,20,f6,20,f6,01,00,21,f6,21,f6,01,00,22,f6,22,f6,\
  01,00,24,f6,24,f6,01,00,30,f6,30,f6,01,00,31,f6,31,f6,01,00,32,f6,32,f6,01,\
  00,34,f6,34,f6,01,00,40,f6,40,f6,01,00,41,f6,41,f6,01,00,42,f6,42,f6,01,00,\
  ff,ff,ff,ff,00,00,00,00,da,17,07,da,b2,00,37,cf,1e,b6,00,44,f6,44,f6,01,00,\
  ff,ff,ff,ff,00,00,00,00,00,18,00,00,01,02,00,f0,03,ff,80,9a,89,3f,01,00,17,\
  00,03,0d,41,10,ff,ff,44,65,6c,6c,20,49,6e,63,2e,00,41,31,36,00,31,31,2f,31,\
  37,2f,32,30,31,36,00,00,01,1b,01,00,01,02,00,04,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,06,03,00,44,65,6c,6c,20,49,6e,63,2e,00,50,72,65,63,69,\
  73,69,6f,6e,20,54,6f,77,65,72,20,37,38,31,30,00,30,36,31,38,00,34,54,4e,51,\
  36,43,32,00,00,02,0f,02,00,01,02,03,04,00,09,00,03,00,0a,00,44,65,6c,6c,20,\
  49,6e,63,2e,00,30,47,57,48,4d,57,00,41,30,32,00,2f,34,54,4e,51,36,43,32,2f,\
  43,4e,37,32,32,30,30,35,42,4b,30,30,33,44,2f,00,00,03,19,03,00,01,07,00,02,\
  00,03,03,03,03,00,00,00,00,00,01,01,03,00,00,00,03,44,65,6c,6c,20,49,6e,63,\
  2e,00,20,20,20,20,20,20,20,00,54,6f,77,65,72,00,00,04,2a,8e,00,01,03,b3,02,\
  f2,06,03,00,ff,fb,eb,bf,03,92,64,00,a0,0f,60,09,41,2b,7f,00,84,00,89,00,00,\
  00,00,06,06,0c,fc,00,b3,00,53,4f,43,4b,45,54,20,31,00,49,6e,74,65,6c,00,49,\
  6e,74,65,6c,28,52,29,20,58,65,6f,6e,28,52,29,20,43,50,55,20,45,35,2d,32,36,\
  32,30,20,76,33,20,40,20,32,2e,34,30,47,48,7a,00,00,04,2a,a2,00,01,03,b3,02,\
  f2,06,03,00,ff,fb,eb,bf,03,92,64,00,a0,0f,60,09,41,2b,93,00,98,00,9d,00,00,\
  00,00,06,06,0c,fc,00,b3,00,53,4f,43,4b,45,54,20,32,00,49,6e,74,65,6c,00,49,\
  6e,74,65,6c,28,52,29,20,58,65,6f,6e,28,52,29,20,43,50,55,20,45,35,2d,32,36,\
  32,30,20,76,33,20,40,20,32,2e,34,30,47,48,7a,00,00,07,13,7f,00,01,80,01,80,\
  01,80,01,02,00,02,00,00,04,01,07,43,50,55,20,49,6e,74,65,72,6e,61,6c,20,4c,\
  31,00,00,07,13,84,00,01,81,01,00,06,00,06,02,00,02,00,00,05,05,07,43,50,55,\
  20,49,6e,74,65,72,6e,61,6c,20,4c,32,00,00,07,13,89,00,01,82,01,00,3c,00,3c,\
  02,00,02,00,00,05,05,0e,43,50,55,20,49,6e,74,65,72,6e,61,6c,20,4c,33,00,00,\
  07,13,93,00,01,80,01,80,01,80,01,02,00,02,00,00,04,01,07,43,50,55,20,49,6e,\
  74,65,72,6e,61,6c,20,4c,31,00,00,07,13,98,00,01,81,01,00,06,00,06,02,00,02,\
  00,00,05,05,07,43,50,55,20,49,6e,74,65,72,6e,61,6c,20,4c,32,00,00,07,13,9d,\
  00,01,82,01,00,3c,00,3c,02,00,02,00,00,05,05,0e,43,50,55,20,49,6e,74,65,72,\
  6e,61,6c,20,4c,33,00,00,08,09,04,00,01,00,02,0f,0e,4a,31,41,31,00,50,53,32,\
  4d,6f,75,73,65,00,00,08,09,05,00,01,00,02,0f,0d,4a,31,41,31,00,4b,65,79,62,\
  6f,61,72,64,00,00,08,09,06,00,01,00,02,08,09,4a,36,41,32,41,00,43,4f,4d,20,\
  41,00,00,08,09,07,00,01,00,02,12,10,4a,32,41,31,00,46,72,6f,6e,74,55,53,42,\
  31,00,00,08,09,08,00,01,00,02,12,10,4a,32,41,31,00,46,72,6f,6e,74,55,53,42,\
  32,00,00,08,09,09,00,01,00,02,12,10,4a,35,41,31,00,46,72,6f,6e,74,55,53,42,\
  33,00,00,08,09,0a,00,01,00,02,12,10,4a,35,41,31,00,46,72,6f,6e,74,55,53,42,\
  34,00,00,08,09,0b,00,01,00,02,0b,1f,4a,32,41,31,00,4c,41,4e,31,00,00,08,09,\
  0c,00,01,00,02,12,10,4a,35,41,31,00,52,65,61,72,55,53,42,31,00,00,08,09,0d,\
  00,01,00,02,12,10,4a,35,41,31,00,52,65,61,72,55,53,42,32,00,00,08,09,0e,00,\
  01,00,02,12,10,4a,35,41,31,00,52,65,61,72,55,53,42,33,00,00,08,09,0f,00,01,\
  00,02,12,10,4a,38,41,31,00,52,65,61,72,55,53,42,34,00,00,08,09,10,00,01,00,\
  02,12,10,4a,38,41,31,00,52,65,61,72,55,53,42,35,00,00,08,09,11,00,01,00,02,\
  12,10,4a,38,41,31,00,52,65,61,72,55,53,42,36,00,00,08,09,12,00,01,00,02,1f,\
  1d,30,30,48,00,4d,49,43,2d,49,4e,00,00,08,09,13,00,01,00,02,1f,1d,30,30,48,\
  00,48,50,2d,4f,55,54,00,00,08,09,14,00,01,00,02,1f,1d,30,30,48,00,4c,49,4e,\
  45,2d,4f,55,54,00,00,08,09,15,00,01,00,02,1f,1d,30,30,48,00,4c,49,4e,45,2d,\
  49,4e,00,00,08,09,16,00,01,ff,00,00,ff,48,44,44,30,00,00,08,09,17,00,01,ff,\
  00,00,ff,48,44,44,31,00,00,08,09,18,00,01,ff,00,00,ff,48,44,44,32,00,00,08,\
  09,19,00,01,ff,00,00,ff,48,44,44,33,00,00,08,09,1a,00,01,ff,00,00,ff,4f,44,\
  44,30,00,00,08,09,1b,00,01,ff,00,00,ff,4f,44,44,31,00,00,08,09,1c,00,01,ff,\
  00,00,10,49,4e,54,5f,55,53,42,31,00,00,08,09,1d,00,01,ff,00,00,10,49,4e,54,\
  5f,55,53,42,32,00,00,08,09,1e,00,01,1f,00,00,1d,49,4e,54,5f,53,50,4b,52,00,\
  00,09,11,1f,00,01,b1,0b,03,04,01,00,0c,01,00,00,01,00,53,6c,6f,74,31,00,00,\
  09,11,20,00,01,b1,0d,04,04,02,00,0c,01,00,00,03,00,53,6c,6f,74,32,00,00,09,\
  11,21,00,01,ab,08,02,03,03,00,0c,01,00,00,ff,00,53,6c,6f,74,33,00,00,09,11,\
  22,00,01,b1,0d,03,04,04,00,0c,01,00,00,04,00,53,6c,6f,74,34,00,00,09,11,23,\
  00,01,ab,0a,02,04,05,00,0c,01,00,00,ff,00,53,6c,6f,74,35,00,00,09,11,24,00,\
  01,06,05,03,03,06,00,0c,01,00,00,0a,10,53,6c,6f,74,36,00,00,0a,06,25,00,85,\
  01,4e,45,54,57,4f,52,4b,5f,4e,41,4d,45,5f,53,54,52,49,4e,47,00,00,0b,05,26,\
  00,06,44,65,6c,6c,20,53,79,73,74,65,6d,00,31,5b,30,36,31,38,5d,00,33,5b,31,\
  2e,30,5d,00,31,32,5b,77,77,77,2e,64,65,6c,6c,2e,63,6f,6d,5d,00,31,34,5b,31,\
  5d,00,31,35,5b,30,5d,00,00,0d,16,e4,f0,01,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,01,65,6e,7c,55,53,7c,69,73,6f,38,38,35,39,2d,31,00,00,10,17,\
  2f,00,03,03,06,00,00,00,08,fe,ff,04,00,00,00,00,00,00,00,00,00,00,00,10,17,\
  57,00,03,03,06,00,00,00,08,fe,ff,04,00,00,00,00,00,00,00,00,00,00,00,11,22,\
  39,00,2f,00,fe,ff,48,00,40,00,00,20,0c,00,01,00,1a,80,00,55,08,02,03,04,05,\
  02,00,00,00,00,4a,07,44,49,4d,4d,31,5f,43,50,55,31,00,48,79,6e,69,78,20,53,\
  65,6d,69,63,6f,6e,64,75,63,74,6f,72,00,20,20,20,20,20,20,20,20,00,20,20,20,\
  20,20,20,20,20,00,48,4d,41,34,31,47,52,37,4d,46,52,38,4e,2d,54,46,20,20,20,\
  00,00,11,22,43,00,2f,00,fe,ff,00,00,00,00,00,00,0c,00,01,00,1a,80,00,00,00,\
  02,03,04,05,00,00,00,00,00,00,00,44,49,4d,4d,33,5f,43,50,55,31,00,44,49,4d,\
  4d,33,5f,43,50,55,31,5f,4d,61,6e,75,66,61,63,74,75,72,65,72,31,00,20,20,20,\
  20,20,20,20,20,20,20,20,20,20,20,20,20,20,00,20,20,20,20,20,20,20,20,20,20,\
  20,20,20,20,20,20,20,20,20,00,44,49,4d,4d,33,5f,43,50,55,31,5f,50,61,72,74,\
  4e,75,6d,62,65,72,00,00,11,22,48,00,2f,00,fe,ff,48,00,40,00,00,20,0c,00,01,\
  00,1a,80,00,55,08,02,03,04,05,02,00,00,00,00,4a,07,44,49,4d,4d,32,5f,43,50,\
  55,31,00,48,79,6e,69,78,20,53,65,6d,69,63,6f,6e,64,75,63,74,6f,72,00,20,20,\
  20,20,20,20,20,20,00,20,20,20,20,20,20,20,20,00,48,4d,41,34,31,47,52,37,4d,\
  46,52,38,4e,2d,54,46,20,20,20,00,00,11,22,52,00,2f,00,fe,ff,00,00,00,00,00,\
  00,0c,00,01,00,1a,80,00,00,00,02,03,04,05,00,00,00,00,00,00,00,44,49,4d,4d,\
  34,5f,43,50,55,31,00,44,49,4d,4d,34,5f,43,50,55,31,5f,4d,61,6e,75,66,61,63,\
  74,75,72,65,72,31,00,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,00,\
  20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,00,44,49,4d,4d,34,\
  5f,43,50,55,31,5f,50,61,72,74,4e,75,6d,62,65,72,00,00,11,22,61,00,57,00,fe,\
  ff,48,00,40,00,00,20,0c,00,01,00,1a,80,00,55,08,02,03,04,05,02,00,00,00,00,\
  4a,07,44,49,4d,4d,31,5f,43,50,55,32,00,48,79,6e,69,78,20,53,65,6d,69,63,6f,\
  6e,64,75,63,74,6f,72,00,20,20,20,20,20,20,20,20,00,20,20,20,20,20,20,20,20,\
  00,48,4d,41,34,31,47,52,37,4d,46,52,38,4e,2d,54,46,20,20,20,00,00,11,22,6b,\
  00,57,00,fe,ff,00,00,00,00,00,00,0c,00,01,00,1a,80,00,00,00,02,03,04,05,00,\
  00,00,00,00,00,00,44,49,4d,4d,33,5f,43,50,55,32,00,44,49,4d,4d,33,5f,43,50,\
  55,32,5f,4d,61,6e,75,66,61,63,74,75,72,65,72,31,00,20,20,20,20,20,20,20,20,\
  20,20,20,20,20,20,20,20,20,00,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,\
  20,20,20,20,00,44,49,4d,4d,33,5f,43,50,55,32,5f,50,61,72,74,4e,75,6d,62,65,\
  72,00,00,11,22,70,00,57,00,fe,ff,48,00,40,00,00,20,0c,00,01,00,1a,80,00,55,\
  08,02,03,04,05,02,00,00,00,00,4a,07,44,49,4d,4d,32,5f,43,50,55,32,00,48,79,\
  6e,69,78,20,53,65,6d,69,63,6f,6e,64,75,63,74,6f,72,00,20,20,20,20,20,20,20,\
  20,00,20,20,20,20,20,20,20,20,00,48,4d,41,34,31,47,52,37,4d,46,52,38,4e,2d,\
  54,46,20,20,20,00,00,11,22,7a,00,57,00,fe,ff,00,00,00,00,00,00,0c,00,01,00,\
  1a,80,00,00,00,02,03,04,05,00,00,00,00,00,00,00,44,49,4d,4d,34,5f,43,50,55,\
  32,00,44,49,4d,4d,34,5f,43,50,55,32,5f,4d,61,6e,75,66,61,63,74,75,72,65,72,\
  31,00,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,00,20,20,20,20,20,\
  20,20,20,20,20,20,20,20,20,20,20,20,20,20,00,44,49,4d,4d,34,5f,43,50,55,32,\
  5f,50,61,72,74,4e,75,6d,62,65,72,00,00,13,1f,34,00,00,00,00,00,ff,ff,ff,00,\
  2f,00,02,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,13,1f,5c,00,\
  00,00,00,01,ff,ff,ff,01,57,00,02,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,14,23,3e,00,00,00,00,00,ff,ff,7f,00,39,00,34,00,01,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,14,23,4d,00,00,00,80,00,ff,\
  ff,ff,00,48,00,34,00,01,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,14,23,66,00,00,00,00,01,ff,ff,7f,01,61,00,5c,00,01,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,14,23,75,00,00,00,80,01,ff,ff,\
  ff,01,70,00,5c,00,01,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,19,09,27,00,00,00,00,00,00,00,00,1b,0f,00,1b,00,1c,65,00,00,dd,00,00,\
  d0,07,01,43,50,55,20,46,61,6e,20,31,00,00,1b,0f,01,1b,01,1c,65,00,01,dd,00,\
  00,d0,07,01,43,50,55,20,46,61,6e,20,32,00,00,1b,0f,02,1b,03,1c,66,00,02,dd,\
  00,00,d0,07,01,4d,65,6d,6f,72,79,20,46,61,6e,20,52,69,67,68,74,00,00,1b,0f,\
  03,1b,04,1c,66,00,03,dd,00,00,d0,07,01,4d,65,6d,6f,72,79,20,46,61,6e,20,4c,\
  65,66,74,00,00,1b,0f,04,1b,08,1c,66,00,04,dd,00,00,d0,07,01,50,43,49,20,46,\
  61,6e,00,00,1c,16,00,1c,01,63,f6,04,0a,fb,e8,03,00,80,01,00,00,dc,00,00,64,\
  00,43,50,55,20,31,20,2d,20,50,45,43,49,00,00,1c,16,01,1c,01,63,f6,04,0a,fb,\
  e8,03,00,80,01,00,01,dc,00,00,64,00,43,50,55,20,32,20,2d,20,50,45,43,49,00,\
  00,1c,16,02,1c,01,68,f6,04,0a,fb,e8,03,00,80,01,00,02,dc,00,00,64,00,54,72,\
  75,65,20,41,6d,62,69,65,6e,74,00,00,1c,16,03,1c,01,68,f6,04,0a,fb,e8,03,00,\
  80,01,00,03,dc,00,00,64,00,4d,65,6d,6f,72,79,20,53,65,6e,73,6f,72,20,31,00,\
  00,1c,16,04,1c,01,68,f6,04,0a,fb,e8,03,00,80,01,00,04,dc,00,00,64,00,4d,65,\
  6d,6f,72,79,20,53,65,6e,73,6f,72,20,32,00,00,20,14,28,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,82,14,b7,f0,24,41,4d,54,00,00,00,00,00,\
  a5,2f,02,00,00,00,00,00,00,83,40,bc,f0,35,00,00,00,00,00,00,00,00,00,00,00,\
  f8,00,44,8d,00,00,00,00,01,00,00,00,01,00,09,00,ea,03,25,00,00,00,00,00,c8,\
  00,3a,15,00,00,00,00,00,00,00,00,22,00,00,00,76,50,72,6f,00,00,00,00,00,00,\
  b1,0c,00,b1,02,00,00,00,00,00,00,00,00,00,d0,10,00,d0,03,07,fe,00,18,06,01,\
  02,00,00,00,00,32,30,31,36,30,32,32,37,00,32,30,31,36,30,37,31,34,00,00,d2,\
  0c,00,d2,f8,03,04,03,06,80,04,03,00,00,d8,09,00,d8,01,02,01,88,00,22,22,00,\
  22,22,00,00,dc,16,00,dc,00,f1,00,00,02,f1,03,f1,00,00,05,f1,00,00,00,00,00,\
  00,00,00,dc,16,01,dc,10,f1,00,00,12,f1,13,f1,00,00,15,f1,00,00,00,00,00,00,\
  00,00,dc,16,02,dc,20,f1,00,00,22,f1,23,f1,00,00,25,f1,00,00,00,00,00,00,00,\
  00,dc,16,03,dc,30,f1,00,00,32,f1,33,f1,00,00,35,f1,00,00,00,00,00,00,00,00,\
  dc,16,04,dc,40,f1,00,00,42,f1,43,f1,00,00,45,f1,00,00,00,00,00,00,00,00,dd,\
  13,00,dd,02,01,00,00,f6,01,f6,02,f6,00,00,04,f6,00,00,00,00,dd,13,01,dd,02,\
  01,00,10,f6,11,f6,12,f6,00,00,14,f6,00,00,00,00,dd,13,02,dd,02,01,00,20,f6,\
  21,f6,22,f6,00,00,24,f6,00,00,00,00,dd,13,03,dd,02,01,00,30,f6,31,f6,32,f6,\
  00,00,34,f6,00,00,00,00,dd,13,04,dd,02,01,00,40,f6,41,f6,42,f6,00,00,44,f6,\
  00,00,00,00,de,10,00,de,01,04,00,00,17,03,03,16,55,01,00,00,00,00,ff,08,2e,\
  00,01,02,00,00,5f,53,49,44,45,33,6b,78,4a,59,62,78,71,44,31,44,00,31,32,33,\
  34,00,5f,53,49,44,41,76,66,39,30,77,37,77,4b,5a,69,5a,00,44,45,4c,4c,00,00,\
  7f,04,e9,f0,00,00

**Comment by nehaheights** [comment]
Hi KunYi,
I have copied data from registry only.
And in windows after using GetSystemFirmwareTable() am getting -
![image](https://user-images.githubusercontent.com/7995783/34554498-314b2454-f153-11e7-8454-ef80a7d73344.png)

**Comment by KunYi** [comment]
I don't know why you just give header not have table data
would be give me your needBufferSize value? or try use Administrators permission to lunch the program? maybe your system have some security settings to block? 
to ref. MSDN (https://msdn.microsoft.com/en-us/library/windows/desktop/ms724379(v=vs.85).aspx)
maybe you can to check 'Return value' sections

**Comment by nehaheights** [comment]
needBufferSize is 5201
It's same with Admin privileges too.
Checking reference you have shared.

**Comment by KunYi** [comment]
so if run the below, to check the 'ret' value How is?
```

>          UINT ret;
>          ...
> 	_tprintf(TEXT("We need prepare %d bytes for recevie SMBIOS/DMI Table\n"), needBufferSize);
> 	pBuff = (LPBYTE) malloc(needBufferSize);
> 	if (pBuff)
> 	{
>                ret = GetSystemFirmwareTable(Signature, 0, pBuff, needBufferSize);
>                ...

 ```

**Comment by nehaheights** [comment]
ret value is same - 5201

**Comment by KunYi** [comment]
Sorry, I don't why the issues now , but suggestion to try WMI interface
or try to use C++ "smbios.cpp/smbios.h" in your code, the code use Single Instance pattern
so just in code to call SMBIOS::getInstance()

and you need modify initialization() to directly apply  getWmiSmbios()

ref. https://github.com/KunYi/DumpSMBIOS/blob/master/DumpSMBIOS/smbios.cpp

**Comment by nehaheights** [comment]
Thanks for all help KunYi :)
Will try this :)

**Comment by KunYi** [comment]
you are welcome
and maybe another way to use 5204 hard code to replace all need needBufferSize parameters functions
just for check issues again!

**Comment by nehaheights** [comment]
getWmiSmbios is fetching right value.

Replacing needBufferSize  with 5204 is not helping.

**Comment by KunYi** [comment]
So sad, but the sound the invoke in OS layer 
Will close the issues
